<a href="https://colab.research.google.com/github/ZoanHy/250plus---Exercises-DS-Bootcamp-in-Python/blob/main/021_030_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 21](#1)
* [Exercise 22](#2)
* [Exercise 23](#3)
* [Exercise 24](#4)
* [Exercise 25](#5)
* [Exercise 26](#6)
* [Exercise 27](#7)
* [Exercise 28](#8)
* [Exercise 29](#9)
* [Exercise 30](#10)

### <a name='0'></a> Import of libraries

In [ ]:
import numpy as np

np.__version__

### <a name='1'></a> Exercise 21
Generate the following numpy array. Save the array to a binary file named _'array.npy'_ and then load that file back into another variable.

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
__Tip:__ Use the _np.save()_ and _np.load()_ functions.


In [ ]:
# enter solution here

### <a name='2'></a> Exercise 22
Generate the following numpy array:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Save the array to a text file named _'array.txt'_ with two decimal places and then load the file back into another variable.

__Tip:__ Use the _np.savetxt()_ and _np.loadtxt()_ functions.


In [ ]:
# enter solution here

### <a name='3'></a> Exercise 23
Generate and convert the following numpy array into a list:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
__Tip:__ Use the _np.array.tolist()_ method.


In [ ]:
# enter solution here

### <a name='4'></a> Exercise 24
The following numpy array is given:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Using the cut operator, transform the array into the following:

* swap rows (first with last)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```

In [ ]:
# enter solution here

* swap columns (reverse order)

```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```

In [ ]:
# enter solution here

* swapp rows and columns (reverse order)

```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
``` 

In [ ]:
# enter solution here

### <a name='5'></a> Exercise 25
The following numpy array:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Transform to array:

```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

__Tip:__ Use the _np.pad()_ function.

In [ ]:
# enter solution here

### <a name='6'></a> Exercise 26
The following numpy array:
```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```

Transform to array:
```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```

__Tip:__ Use the cut operator and assign the appropriate values.


In [ ]:
# enter solution here

### <a name='7'></a> Exercise 27
Combine the following arrays: $ A $ and $ B $ into one array.

```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```

__The expected result:__

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```

__Tip:__ Use the _np.append()_ function.


In [ ]:
# enter solution here

### <a name='8'></a> Exercise 28
Use the $ A $ and $ B $ arrays below to extract the common elements (intersection) of the arrays.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```
__Tip:__ Use the _np.intersect1d()_ function.

In [ ]:
# enter solution here

### <a name='9'></a> Exercise 29
The following numpy array $ A $ is given.
Find the unique values of this array.

```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```

__Tip:__ Use the _np.unique()_ function.

In [ ]:
# enter solution here

### <a name='10'></a> Exercise 30
The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return indexes with maximum values for a given row.

__Tip:__ Use the _np.argmax()_ function.

In [ ]:
# enter solution here