<a href="https://colab.research.google.com/github/ZoanHy/250plus---Exercises-DS-Bootcamp-in-Python/blob/main/031_040_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 31](#1)
* [Exercise 32](#2)
* [Exercise 33](#3)
* [Exercise 34](#4)
* [Exercise 35](#5)
* [Exercise 36](#6)
* [Exercise 37](#7)
* [Exercise 38](#8)
* [Exercise 39](#9)
* [Exercise 40](#10)

### <a name='0'></a> Import of libraries

In [ ]:
import numpy as np

np.__version__

### <a name='1'></a> Exercise 31
Sort the array $ A $ below:
* by row (ascending)
* by column (ascending)

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```
__Tip:__ Use the _np.sort()_ function.


In [ ]:
# enter solution here

### <a name='2'></a> Exercise 32
Extract all elements of the $ A $ array with a value greater than 8.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

In [ ]:
# enter solution here

### <a name='3'></a> Exercise 33
The following array $ A $ is given. Replace elements above 10 with a fixed value of 10 (truncation to 10).

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Tip:__ Use the _np.where()_ function.


In [ ]:
# enter solution here

### <a name='4'></a> Exercise 34
Present the following $ A $ two-dimensional array as a "flattened" one-dimensional array.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Tip:__ Use the _np.ravel()_ function.

In [ ]:
# enter solution here

### <a name='5'></a> Exercise 35
Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 0.0.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```

__Tip:__ Use the _np.zeros_like()_ function.

In [ ]:
# enter solution here

### <a name='6'></a> Exercise 36

Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 9.99.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__

```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```

__Tip:__ Use the function _np.full_like()_.




In [ ]:
# enter solution here

### <a name='7'></a> Exercise 37
Build a two-dimensional array (lower triangular matrix) below:
```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
__Tip:__ Use the _np.tri()_ function.

In [ ]:
# enter solution here

### <a name='8'></a> Exercise 38
Create any $ (2, 3, 4) $ 3-dimensional array.

In [ ]:
# enter solution here

### <a name='9'></a> Exercise 39
Generate a two-dimensional array _(200, 300)_ filled with random values from 0 to 255 (inclusive) with data type _np.uint8_ and assign to the variable _image_.

In [ ]:
# enter solution here

Then run the following block of code. As a result, you'll get a preview of the randomly generated black and white image.

In [ ]:
from google.colab.patches import cv2_imshow

cv2_imshow(image)

### <a name='10'></a> Exercise 40
Sort the array _image_ from the previous exercise along the row in ascending order. Then display the image with the _cv2_imshow()_ function.

In [ ]:
# enter solution here

Sort the array _image_ from the previous exercise along the column in ascending order. Then display the image with the _cv2_imshow()_ function.

In [ ]:
# enter solution here