<a href="https://colab.research.google.com/github/ZoanHy/250plus---Exercises-DS-Bootcamp-in-Python/blob/main/071_080_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 71](#1)
* [Exercise 72](#2)
* [Exercise 73](#3)
* [Exercise 74](#4)
* [Exercise 75](#5)
* [Exercise 76](#6)
* [Exercise 77](#7)
* [Exercise 78](#8)
* [Exercise 79](#9)
* [Exercise 80](#10)

### <a name='0'></a> Import of libraries

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.22.4'

### <a name='1'></a> Exercise 71
The following $ A $ array is given:
```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
From the second row of the $ A $ array, randomly shuffle the rows in the array.

__Tip:__ Use the _np.random.shuffle()_ function.


In [3]:
# enter solution here

A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])

A

array([['id', 'price'],
       ['002', '4.99'],
       ['005', '1.49'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['004', '2.49']], dtype='<U32')

### <a name='2'></a> Exercise 72
The following array $ A $ is given:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Return an array of indexes that will sort the array $ A $ in ascending order.

__Expected result:__

```
array([5, 2, 1, 0, 4, 3])
```
__Tip:__ Use the _np.argsort()_ function.


In [4]:
# enter solution here

A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Exercise 73

The following array $ A $ is given:
```
A = np.random.randn(10, 8)
```
Round the values of this array to three decimal places.

__Tip:__ Use the function _np.round()_.


In [5]:
# enter solution here

A = np.random.randn(10, 8)

np.round(A, 3)

array([[ 0.474,  1.368, -0.917, -0.124, -2.011, -0.493,  0.393, -0.929],
       [ 0.08 , -0.16 ,  0.022, -0.428, -0.532, -0.117,  0.222, -0.768],
       [ 0.142, -0.035,  1.134, -0.105, -0.525,  1.913, -2.027,  1.119],
       [ 0.779, -1.101,  1.13 ,  0.373, -0.386, -1.159,  0.566, -0.704],
       [-1.378, -0.353, -0.461,  0.067, -0.176,  1.201,  0.698, -0.172],
       [-0.907,  1.189,  0.786,  2.656,  0.263,  1.642,  0.461,  0.086],
       [-1.51 ,  0.722, -0.843, -0.513, -0.044, -0.275, -1.563, -0.796],
       [ 0.931,  0.678,  0.698,  0.174,  0.662,  0.241, -0.168,  1.165],
       [-0.246, -0.77 ,  1.212,  1.233, -1.574,  0.638, -2.044,  1.069],
       [-0.934,  0.784, -0.615,  0.333, -1.381, -0.281, -0.06 ,  0.961]])

### <a name='4'></a> Exercise 74
Determine the roots of the polynomial:
* $W(x) = 4x^2 + 5x + 1$

Check the solution.

__Tip:__ Use the _np.roots()_ and _np.polyval()_ functions.

In [7]:
# enter solution here

W = np.array([4, 5, 1])

np.roots(W)

array([-1.  , -0.25])

In [9]:
np.polyval(W, -1), np.polyval(W, -0.25)

(0, 0.0)

### <a name='5'></a> Exercise 75
Determine the roots of polynomials:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Tip:__ Use the _np.roots()_ function.


In [11]:
# enter solution here

Q = np.array([2, 4, -5, 1])
R = np.array([2, 0, -5, 1])

print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


### <a name='6'></a> Exercise 76
Polynomials are given:
* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [12]:
# enter solution here

W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Perform:
* $ W (x) + Q (x) $

In [13]:
# enter solution here

np.polyadd(W, Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [14]:
# enter solution here

np.polysub(W, Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [15]:
# enter solution here

np.polymul(W, Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [16]:
# enter solution here

np.polyadd(W, 2 * Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Exercise 77
The array below is given:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```
Use the sign function for the array $ A $. As a reminder, the function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values.

__Expected result:__

```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Tip:__ Use the _np.sign()_ function.

In [17]:
# enter solution here

A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Exercise 78
Using the _np.arange()_ function, generate the following array:

```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```


In [18]:
# enter solution here

np.arange('2021-01', '2021-02', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')

### <a name='9'></a> Exercise 79

Using the _np.arange()_ function, generate the following array:

```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```


In [20]:
# enter solution here

np.arange('2021-01', '2022-01', dtype='datetime64[M]').reshape(-1, 3)

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Exercise 80
Using the _np.datetime64()_ function, generate today's date (the date you were doing the exercise).

In [21]:
# enter solution here

np.datetime64('today')

numpy.datetime64('2023-03-19')