## Pandas

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 191](#1)
* [Exercise 192](#2)
* [Exercise 193](#3)
* [Exercise 194](#4)
* [Exercise 195](#5)
* [Exercise 196](#6)
* [Exercise 197](#7)
* [Exercise 198](#8)
* [Exercise 199](#9)
* [Exercise 200](#10)

### <a name='0'></a> Import of libraries

In [35]:
import numpy as np
import pandas as pd

np.__version__

'1.23.3'

### <a name='1'></a> Exercise 191
Create the _DataFrame_ object from the _data_ dictionary below and assign it to the _df_ variable.

```
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}
```

In [36]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

# enter solution here

df = pd.DataFrame(data)


Display basic information about the object _df_.

In [37]:
# enter solution here

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


Convert variables to types:
* size -> _category_
* color -> _category_
* gender -> _category_
* weight -> _float_
* bought -> _category_

In [38]:
# enter solution here

name_categories = list(df.select_dtypes(include="object").columns)

for col in name_categories:
    df[col] = df[col].astype("category")

df["weight"] = df["weight"].astype("float")

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


### <a name='2'></a> Exercise 192
Use the _scikit-learn_ machine learning library and the _LabelEncoder_ class to code 0-1 of the _bought_ variable. Assign changes to the _df_ object permanently and display the object.

In [39]:
# enter solution here

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

df['bought'] = le.fit_transform(df['bought'])

df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

Use the appropriate method of the _LabelEncoder_ class to restore the original values of the _bought_ variable. Note the type of the _bought_ variable.

In [40]:
# enter solution here

df['bought'] = le.inverse_transform(df['bought'])
df['bought'] = df['bought'].astype('category')

df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


### <a name='3'></a> Exercise 193
Using the machine learning library _scikit-learn_ and the _OneHotEncoder_ class, encode 0-1 of the _size_ variable. Don't assign changes to the _df_ object.

Use the `sparse = False` parameter of the _OneHotEncoder_ class.

In [42]:
# enter solution here

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(sparse=False)

enc.fit_transform(df[["size"]])


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

Using the machine learning library _scikit-learn_ and the _OneHotEncoder_ class, encode 0-1 of the _size_ variable. Don't assign changes to the _df_ object.

Use the parameter `sparse = False` and `drop = first` of the _OneHotEncoder_ class.

In [43]:
# enter solution here

enc = OneHotEncoder(sparse=False, drop='first')

enc.fit_transform(df[["size"]])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

### <a name='4'></a> Exercise 194
Using the _pandas_ library and the _get_dummies()_ function, present all categorical variables of the _df_ object in the form of 0-1 encoding. Don't assign changes permanently to the _df_ object.

In [44]:
# enter solution here

pd.get_dummies(data=df)

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0       0       0        1           0            0          1   
1   89.0   450.0       1       0        0           0            1          0   
2   99.0   300.0       0       1        0           1            0          0   
3  129.0   380.0       1       0        0           0            1          0   
4   79.0   410.0       0       1        0           0            0          1   

   gender_female  gender_male  bought_no  bought_yes  
0              1            0          0           1  
1              0            1          1           0  
2              0            1          0           1  
3              1            0          1           0  
4              1            0          0           1

Using the _pandas_ library and the _get_dummies()_ function, present all categorical variables of the _df_ object in the form of 0-1 encoding. Use the `drop_first = True` parameter. Don't assign changes permanently to the _df_ object.

In [45]:
# enter solution here

pd.get_dummies(data=df, drop_first=True)


price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0       0        1            0          1            0   
1   89.0   450.0       0        0            1          0            1   
2   99.0   300.0       1        0            0          0            1   
3  129.0   380.0       0        0            1          0            0   
4   79.0   410.0       1        0            0          1            0   

   bought_yes  
0           1  
1           0  
2           1  
3           0  
4           1

Using the _pandas_ library and the _get_dummies()_ function, present the _size_ variable of the _df_ object in the form of 0-1 encoding. Use the `drop_first = True` parameter. Don't assign changes permanently to the _df_ object.

In [46]:
# enter solution here

pd.get_dummies(data=df, columns=['size'], drop_first=True)


color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes       0        1
1  green    male   89.0   450.0     no       0        0
2   blue    male   99.0   300.0    yes       1        0
3  green  female  129.0   380.0     no       0        0
4    red  female   79.0   410.0    yes       1        0

### <a name='5'></a> Exercise 195
Use the _scikit-learn_ machine learning library and the _StandardScaler_ class to scale the _weight_ variable. Don't assign changes to the _df_ object.

In [47]:
# enter solution here

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit_transform(df[["weight"]])


array([[ 1.3660019 ],
       [ 0.62360956],
       [-1.60356745],
       [-0.41573971],
       [ 0.02969569]])

### <a name='6'></a> Exercise 196
Load the _data_ dictionary again into the _DataFrame_ object named _df_.

In [48]:
# enter solution here

df = pd.DataFrame(data)

df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

Prepare the data for the machine learning model:
* using the LabelEncoder class, encode 0-1 of the _bought_ variable
* standardize the variables _weight_ and _price_
* encode 0-1 categorical variables using the function _get_dummies()._

Assign changes to the _df_prep_ variable.

In [49]:
# enter solution here

from sklearn import preprocessing

df_prep = df.copy()
le = preprocessing.LabelEncoder()

df_prep["bought"] = le.fit_transform(df["bought"])

scaler = preprocessing.StandardScaler()
df_prep[["weight", "price"]] = scaler.fit_transform(df[["weight", "price"]])

df_prep = pd.get_dummies(df_prep, drop_first=True)

df_prep


price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0

### <a name='7'></a> Exercise 197
Copy the _df_prep_ object to the _data_ variable. Then pop the _bought_ column from this object and assign it to the _target_ variable.

In [50]:
# enter solution here

data = df_prep.copy()

target = data.pop('bought')

Display the first 5 rows of _data_. Make sure the _bought_ column is not in it.

In [51]:
# enter solution here

data.head()

price    weight  size_M  size_XL  color_green  color_red  gender_male
0  1.845062  1.366002       0        1            0          1            0
1 -0.691898  0.623610       0        0            1          0            1
2 -0.461266 -1.603567       1        0            0          0            1
3  0.230633 -0.415740       0        0            1          0            0
4 -0.922531  0.029696       1        0            0          1            0

Display the first 5 rows of _target_.

In [52]:
# enter solution here

target.head()

0    1
1    0
2    1
3    0
4    1
Name: bought, dtype: int32

### <a name='8'></a> Exercise 198
Using the _scikit-learn_ library and the _train_test_split_ function, divide the data from the _data_ and _target_ objects into a training set (_X\_train_, _y\_train_) and a test set (_X\_test_, _y\_test_). Assign 20% of the samples to the test set.

Display object size:
* _X\_train_
* _X\_test_
* _y\_train_
* _y\_test_

In [53]:
# enter solution here
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

print(f'X_train: {X_train.shape}')
print(f'X_test: {X_test.shape}')
print(f'y_train: {y_train.shape}')
print(f'y_test: {y_test.shape}')


X_train: (4, 7)
X_test: (1, 7)
y_train: (4,)
y_test: (1,)


### <a name='9'></a> Exercise 199
Combine _X\_train_ and _X\_test_ objects into one _DataFrame_ object named _X_.

In [54]:
# enter solution here

X = pd.concat([X_train, X_test])

X

price    weight  size_M  size_XL  color_green  color_red  gender_male
1 -0.691898  0.623610       0        0            1          0            1
4 -0.922531  0.029696       1        0            0          1            0
0  1.845062  1.366002       0        1            0          1            0
2 -0.461266 -1.603567       1        0            0          0            1
3  0.230633 -0.415740       0        0            1          0            0

### <a name='10'></a> Exercise 200
Combine the _y\_train_ and _y\_test_ objects into one _DataFrame_ object named _y_.

In [55]:
# enter solution here

y = pd.concat([y_train, y_test])

y

1    0
4    1
0    1
2    1
3    0
Name: bought, dtype: int32

Combine _X_ and _y_ objects into one _DataFrame_ object.

In [56]:
# enter solution here

pd.concat([X, y], axis = 1)

price    weight  size_M  size_XL  color_green  color_red  gender_male  \
1 -0.691898  0.623610       0        0            1          0            1   
4 -0.922531  0.029696       1        0            0          1            0   
0  1.845062  1.366002       0        1            0          1            0   
2 -0.461266 -1.603567       1        0            0          0            1   
3  0.230633 -0.415740       0        0            1          0            0   

   bought  
1       0  
4       1  
0       1  
2       1  
3       0